### ISSUE TITLE
Set Login Page as a Default Page

### ISSUE THREAD

**Issue by GudBoiNero** [Minuteman-PWD-2025/Biotech-CSI#19]
**Description of the feature. Enough for anyone to follow.**
While we do not have a token in our session, we should always redirect the user to the login page until they get a token.

**Describe the features requirements**

**Comment by ihaveapatricklmao** [comment]
I have been looking into this lately and it seems that we can use Routers to change pages and set default pages. I am going to look into this more to see if this is a possible solution.
